apiVersion: v1
kind: Secret
metadata:
  labels:
    app: db
  name: db
  namespace: tekton-hub
data:
  database-name: c2FtcGxlZGI=
  database-password: T1lGV2pJazUyUk5KRHBOTQ==
  database-user: dXNlck9KNw==
type: Opaque
